[workspace]

members = ["bootloader", "driver", "filesystem", "kernel", "program", "stdio"]

resolver = "2"


[profile.release]
debug = true
strip = false
opt-level = 'z'
codegen-units = 1
lto = true
panic = 'abort'
